import { StyleSheet } from 'react-native';

export const historyStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f5f5f5',
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 16,
        backgroundColor: 'white',
        borderBottomWidth: 1,
        borderBottomColor: '#e0e0e0',
    },
    backButton: {
        marginRight: 16,
        padding: 8,
    },
    title: {
        fontSize: 18,
        fontWeight: '600',
        color: '#333',
    },
    actionBar: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        padding: 16,
        backgroundColor: 'white',
        borderBottomWidth: 1,
        borderBottomColor: '#e0e0e0',
    },
    actionButton: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 8,
        backgroundColor: '#f8f9fa',
        position: 'relative',
    },
    actionButtonText: {
        marginLeft: 4,
        fontSize: 14,
        color: '#007AFF',
        fontWeight: '500',
    },
    filterDot: {
        position: 'absolute',
        top: 2,
        right: 2,
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: '#FF3B30',
    },
    list: {
        flex: 1,
        padding: 16,
    },
    historyCard: {
        backgroundColor: 'white',
        borderRadius: 12,
        padding: 16,
        marginBottom: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    historyHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 12,
    },
    historyInfo: {
        flex: 1,
        marginRight: 16,
    },
    historyName: {
        fontSize: 16,
        fontWeight: '600',
        color: '#333',
        marginBottom: 4,
    },
    historyCode: {
        fontSize: 14,
        color: '#666',
        marginBottom: 4,
    },
    historyPrinter: {
        fontSize: 12,
        color: '#888',
        flexDirection: 'row',
        alignItems: 'center',
    },
    historyStatus: {
        alignItems: 'center',
    },
    statusText: {
        fontSize: 12,
        fontWeight: '500',
        marginTop: 4,
    },
    historyDetails: {
        borderTopWidth: 1,
        borderTopColor: '#f0f0f0',
        paddingTop: 12,
        gap: 4,
    },
    historyDate: {
        fontSize: 12,
        color: '#666',
        flexDirection: 'row',
        alignItems: 'center',
    },
    historyDuration: {
        fontSize: 12,
        color: '#666',
    },
    historyIp: {
        fontSize: 12,
        color: '#888',
    },
    errorContainer: {
        marginTop: 8,
        padding: 8,
        backgroundColor: '#ffebee',
        borderRadius: 6,
        borderLeftWidth: 3,
        borderLeftColor: '#F44336',
    },
    errorText: {
        fontSize: 12,
        color: '#d32f2f',
        fontStyle: 'italic',
    },
    emptyState: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 40,
    },
    emptyText: {
        marginTop: 16,
        fontSize: 16,
        color: '#666',
        textAlign: 'center',
        lineHeight: 24,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    statsModal: {
        width: '90%',
        maxHeight: '80%',
        backgroundColor: 'white',
        borderRadius: 16,
        overflow: 'hidden',
    },
    filterModal: {
        width: '90%',
        maxHeight: '70%',
        backgroundColor: 'white',
        borderRadius: 16,
        overflow: 'hidden',
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 20,
        borderBottomWidth: 1,
        borderBottomColor: '#e0e0e0',
        backgroundColor: '#f8f9fa',
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#333',
    },
    statsContent: {
        padding: 20,
    },
    statItemColumn: {
        flexDirection: 'column',
        justifyContent: 'flex-start',
        alignItems: 'flex-start',
    },
    statItem: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#f0f0f0',
    },
    statLabel: {
        fontSize: 14,
        color: '#666',
        flex: 1,
    },
    statValue: {
        fontSize: 16,
        fontWeight: '600',
        color: '#333',
        textAlign: 'right',
    },
    filterContent: {
        padding: 20,
    },
    filterOption: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderRadius: 8,
        marginBottom: 8,
        backgroundColor: '#f8f9fa',
    },
    filterOptionSelected: {
        backgroundColor: '#e3f2fd',
        borderWidth: 1,
        borderColor: '#007AFF',
    },
    filterOptionText: {
        fontSize: 14,
        color: '#333',
        flex: 1,
    },
    filterOptionTextSelected: {
        color: '#007AFF',
        fontWeight: '500',
    },
});
